SongContest/SongContest.Web/Models/CreateComposerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using SongContest.Core.Entities;

namespace SongContest.Web.Models
{
    public class CreateComposerViewModel
    {
        public int ParticipantId { get; set; }
        public string CountryName { get; set; }
        public string SongTitle { get; set; }
        [Required] public string NewComposerName { get; set; }

        public IEnumerable<string> ComposerNames { get; set; }

        public CreateComposerViewModel() {}

        public CreateComposerViewModel(Participant participant, IEnumerable<string> composerNames)
        {
            if (participant == null) throw new ArgumentNullException(nameof(participant));

            CountryName = participant.Country?.Name ??
                          throw new ArgumentNullException(nameof(participant), 
                              "Country of participant was null! (maybe not included in query?)");

            ParticipantId = participant.Id;
            SongTitle = participant.SongTitle;
            ComposerNames = composerNames;
        }

        public ParticipantComposer GetComposer() => new()
        {
            ParticipantId = ParticipantId,
            Name = NewComposerName
        };
    }
}

SongContest/SongContest.Web/Models/CreateParticipantViewModel.cs
using System.ComponentModel.DataAnnotations;
using SongContest.Core.Entities;

namespace SongContest.Web.Models
{
    public class CreateParticipantViewModel
    {
        [Required] public string CountryName { get; set; }
        [Required] public string SongTitle { get; set; }
        [Required] public string ActorName { get; set; }

        public CreateParticipantViewModel() {}

        public Participant GetParticipant() => new()
        {
            SongTitle = SongTitle,
            ActorName = ActorName,
            Country = new Country { Name = CountryName }
        };
    }
}

SongContest/SongContest.Web/Models/ErrorViewModel.cs
using System;

namespace SongContest.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SongContest/SongContest.Web/Models/ParticipantResultsViewModel.cs
using System.Collections.Generic;
using SongContest.Core.DataTransferObjects;

namespace SongContest.Web.Models
{
    public class ParticipantResultsViewModel
    {
        public IEnumerable<string> CountryNames { get; set; }
        public IEnumerable<ParticipantResultsDto> Participants { get; set; }

        public ParticipantResultsViewModel() {}
    }
}

SongContest/SongContest.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SongContest.Web.Models;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using SongContest.Core.Contracts;
using SongContest.Core.Entities;
using SongContest.Web.DataTransferObjects;

namespace SongContest.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public HomeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var participants = await _unitOfWork.Participants.GetAsync(
                filter: null,
                orderBy: query => query.OrderBy(p => p.Country.Name),
                includeProperties: nameof(Participant.Country)
            );

            return View(participants.Select(p => new ParticipantOverviewDto(
                    Id: p.Id,
                    Country: p.Country.Name,
                    Song: p.SongTitle,
                    Name: p.ActorName
                )));
        }

        [HttpGet]
        public async Task<IActionResult> GetResultOverview()
        {
            var countryNames = await _unitOfWork.Countries.GetAsync(
                    orderBy: query => query.OrderBy(c => c.Name)
                );

            var viewModel = new ParticipantResultsViewModel
            {
                CountryNames = countryNames.Select(c => c.Name),
                Participants = await _unitOfWork.Participants.GetParticipantResults()
            };

            return View(viewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SongContest/SongContest.Web/Controllers/ParticipantComposerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using SongContest.Core.Contracts;
using SongContest.Core.Entities;
using SongContest.Web.Models;

namespace SongContest.Web.Controllers
{
    public class ParticipantComposerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ParticipantComposerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            var participant = await _unitOfWork.Participants
                .GetByIdAsync(id, nameof(Participant.Country));

            var composerNames = await _unitOfWork.Composers.GetComposerNamesOfParticipant(id);

            return View(new CreateComposerViewModel(participant, composerNames));
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateComposerViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var composer = viewModel.GetComposer();
                await _unitOfWork.Composers.AddAsync(composer);

                try
                {
                    await _unitOfWork.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            var participant = await _unitOfWork.Participants
                .GetByIdAsync(viewModel.ParticipantId, nameof(Participant.Country));

            var composerNames = await _unitOfWork.Composers.GetComposerNamesOfParticipant(viewModel.ParticipantId);

            return View(new CreateComposerViewModel(participant, composerNames));
        }
    }
}

SongContest/SongContest.Web/Controllers/ParticipantController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using SongContest.Core.Contracts;
using SongContest.Web.Models;

namespace SongContest.Web.Controllers
{
    public class ParticipantController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ParticipantController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreateParticipantViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateParticipantViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var participant = viewModel.GetParticipant();
                await _unitOfWork.Participants.AddAsync(participant);

                try
                {
                    await _unitOfWork.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
                catch (ValidationException ex)
                {
                    var validationResult = ex.ValidationResult;

                    if (validationResult.MemberNames.Any())
                    {
                        foreach (var memberName in validationResult.MemberNames)
                        {
                            ModelState.AddModelError(memberName == "Name" ? "CountryName" : memberName, validationResult.ToString());
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", validationResult.ToString());
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return View(viewModel);
        }
    }
}

SongContest/SongContest.Web/Views/Home/GetResultOverview.cshtml
@model ParticipantResultsViewModel
@{
    ViewData["Title"] = "Teilnehmer Ergebnisse";
}

<h2>@ViewData["Title"]</h2>

<table class="table">
    <tr>
        <th>Land</th>
        <th>Gesamtpunkte</th>
        @foreach(var county in Model.CountryNames)
        {
            <th>@county</th>
        }
    </tr>
    @foreach (var participant in Model.Participants)
    {
        <tr>
            <td>@participant.Country</td>
            <td>@participant.Points</td>
            @foreach (var result in participant.Results)
            {
                <td>@result.Points</td>
            }
        </tr>
    }
</table>

SongContest/SongContest.Web/Views/Home/Index.cshtml
@model IEnumerable<SongContest.Web.DataTransferObjects.ParticipantOverviewDto>
@{
    ViewData["Title"] = "Home Page";
}

<div class="m-1">
    <a asp-action="GetResultOverview">Gesamtergebnis anzeigen</a>
</div>

<div class="m-2">
    <a asp-controller="Participant" asp-action="Create" class="btn btn-primary text-white">Neuen Teilnehmer anlegen</a>
</div>

<table class="table table-striped">
    <thead>
    <tr>
        <th>Teilnehmerland</th>
        <th>Song</th>
        <th>Sänger/Sängerin</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Country</td>
            <td>@item.Song</td>
            <td>@item.Name</td>
            <td>
                <a asp-controller="ParticipantComposer" asp-action="Create" asp-route-id="@item.Id">Komponisten bearbeiten</a>
            </td>
        </tr>
    }
    </tbody>
</table>

SongContest/SongContest.Web/Views/Participant/Create.cshtml
@model CreateParticipantViewModel
@{
    ViewData["Title"] = "Teilnehmer anlegen";
}


<h2>@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Land</label>
                <input asp-for="CountryName" class="form-control" />
                <span asp-validation-for="CountryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Song-Titel</label>
                <input asp-for="SongTitle" class="form-control" />
                <span asp-validation-for="SongTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Sänger/Sängerin</label>
                <input asp-for="ActorName" class="form-control" />
                <span asp-validation-for="ActorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Zurück</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SongContest/SongContest.Web/Views/ParticipantComposer/Create.cshtml
@model CreateComposerViewModel
@{
    ViewData["Title"] = "Komponisten bearbeiten";
}

<h2>@ViewData["Title"]</h2>

<h3>Land: @Model.CountryName</h3>
<h3>Song: @Model.SongTitle</h3>

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="NewComposerName" class="control-label"></label>
        <input asp-for="NewComposerName" class="form-control" />
        <span asp-validation-for="NewComposerName" class="text-danger"></span>
    </div>
    <input asp-for="ParticipantId" type="hidden" />
    <div class="form-group">
        <input type="submit" value="Hinzufügen" class="btn btn-primary" />
    </div>
</form>

<table class="table table-striped">
    <tr><th>Komponist</th></tr>
    @foreach (var composer in Model.ComposerNames)
    {
        <tr><td>@composer</td></tr>
    }
</table>

<div>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Zurück zur Übersicht</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SongContest/SongContest.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SongContest.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SongContest.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SongContest.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>